### ISSUE TITLE
Cannot open project using Visual Studio 2015

### ISSUE THREAD

**Issue by libreliodev** [libreliodev/windows8#88]
There seems to be an answer here: https://social.msdn.microsoft.com/Forums/vstudio/en-US/9e9100c9-e25d-4030-a103-5f88f6fadfb0/visual-studio-2015-missing-features-metro-development?forum=visualstudiogeneral

**Comment by libreliodev** [comment]
@voyagerj Hope you are well. Do you have suggestions about the proper way to solve this issue? 
Many thanks.

**Comment by libreliodev** [comment]
Tried downloading the 8.1 sdk from https://msdn.microsoft.com/en-US/windows/desktop/ff851942.aspx

Still no way open project.

**Comment by voyagerj** [comment]
Hi! I'm fine, thanks! Hm.. it's looke like something wrong with your version of VS 2015. I just install fresh version of VS2015 (with WinPhone support checkbox during installation) and project for Windows 8.1 success compiled. Project Windows 8 should be retargeting to Win8.1 (VS 2015 not support WinStore 8.0 according to 
https://www.visualstudio.com/en-us/products/visual-studio-2015-compatibility-vs.aspx).

**Comment by libreliodev** [comment]
@voyagerj Many thanks.
